
import pymupdf
import re


def extract_uploaded_pdf(uploaded_file):
    """Extract page-aware text from an uploaded PDF."""

    pdf_bytes = uploaded_file.read()

    doc = pymupdf.open(
        stream=pdf_bytes,
        filetype="pdf"
    )

    pages = []

    for page_number, page in enumerate(doc, start=1):
        pages.append({
            "page": page_number,
            "text": page.get_text()
        })

    doc.close()

    return pages


def create_uploaded_chunks(
    pages,
    chunk_size=1500,
    overlap=300
):
    """Create page-aware text chunks."""

    chunks = []

    for page in pages:

        text = page["text"]

        start = 0

        while start < len(text):

            end = start + chunk_size

            chunk_text = text[start:end].strip()

            if chunk_text:
                chunks.append({
                    "page": page["page"],
                    "text": chunk_text
                })

            start += chunk_size - overlap

    return chunks


def extract_financial_metrics(pages):
    """Extract key financial metrics from financial statement pages."""

    metrics = {
        "Revenue": None,
        "Net Income": None,
        "Operating Income": None,
        "Operating Cash Flow": None,
        "Total Assets": None,
        "Total Liabilities": None,
        "Total Equity": None,
        "Cash & Equivalents": None,
        "Long-Term Debt": None
    }

    statement_pages = []

    for page in pages:

        text = page["text"]
        lower = text.lower()

        if any(keyword in lower for keyword in [
            "statements of operations",
            "statements of income",
            "statement of operations",
            "statement of income",
            "balance sheets",
            "balance sheet",
            "statements of cash flows",
            "statement of cash flows"
        ]):

            statement_pages.append(text)

    statement_text = "\n".join(statement_pages)

    statement_text = statement_text.replace(",", "")

    statement_text = re.sub(
        r"[ \t]+",
        " ",
        statement_text
    )

    def find_value(label_patterns):

        for label in label_patterns:

            pattern = (
                label +
                r".{0,80}?"
                r"(\d{2,}(?:\.\d+)?)"
            )

            matches = re.findall(
                pattern,
                statement_text,
                re.IGNORECASE | re.DOTALL
            )

            if matches:

                values = [
                    float(value)
                    for value in matches
                ]

                return max(values)

        return None

    metrics["Revenue"] = find_value([
        r"total net sales",
        r"total revenue"
    ])

    metrics["Net Income"] = find_value([
        r"net income"
    ])

    metrics["Operating Income"] = find_value([
        r"operating income"
    ])

    metrics["Operating Cash Flow"] = find_value([
        r"cash generated by operating activities",
        r"net cash provided by operating activities"
    ])

    metrics["Total Assets"] = find_value([
        r"total assets"
    ])

    liability_match = re.search(
        r"total liabilities\s+(\d{5,})\s+\d{5,}",
        statement_text,
        re.IGNORECASE
    )

    if liability_match:
        metrics["Total Liabilities"] = float(
            liability_match.group(1)
        )

    metrics["Total Equity"] = find_value([
        r"total shareholders[’']? equity",
        r"total stockholders[’']? equity",
        r"total equity"
    ])

    metrics["Cash & Equivalents"] = find_value([
        r"cash and cash equivalents"
    ])

    debt_match = re.search(
        r"non-current liabilities:.*?term debt\s+(\d{5,})\s+\d{5,}",
        statement_text,
        re.IGNORECASE | re.DOTALL
    )

    if debt_match:
        metrics["Long-Term Debt"] = float(
            debt_match.group(1)
        )

    return metrics
import numpy as np


def search_uploaded_chunks(
    question,
    chunks,
    embeddings,
    embedding_model,
    top_k=5
):
    """Find the most relevant chunks from the uploaded report."""

    query_embedding = embedding_model.encode(
        [question]
    )[0]

    similarities = np.dot(
        embeddings,
        query_embedding
    ) / (
        np.linalg.norm(embeddings, axis=1)
        * np.linalg.norm(query_embedding)
    )

    top_indices = np.argsort(
        similarities
    )[::-1][:top_k]

    results = []

    for index in top_indices:

        results.append({
            "page": chunks[index]["page"],
            "text": chunks[index]["text"],
            "score": float(
                similarities[index]
            )
        })

    return results
from groq import Groq


def ask_uploaded_report(
    question,
    chunks,
    embeddings,
    embedding_model,
    api_key,
    top_k=5
):
    """Answer a question using the uploaded annual report."""

    sources = search_uploaded_chunks(
        question,
        chunks,
        embeddings,
        embedding_model,
        top_k=top_k
    )

    context = "\n\n".join(
        [
            f"[Page {source['page']}]\n{source['text']}"
            for source in sources
        ]
    )

    client = Groq(
        api_key=api_key
    )

    prompt = f"""
You are an AI assistant answering questions about a company's annual report.

Use ONLY the provided annual report context.

If the answer cannot be found in the provided context, say:
"I could not find that information in the uploaded annual report."

Before saying the information is unavailable:
1. Review ALL provided context pages.
2. Look for the exact metric, value, table, or statement requested.
3. Prefer direct financial statement values or explicit numerical tables over indirect references.
4. If a relevant value is present on any provided page, use it.
5. Do not calculate or infer a value unless the calculation is explicitly supported by the report.

Do not invent facts.

Always cite the relevant page number using this format:
[Page X]

Annual Report Context:
{context}

Question:
{question}
"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    return answer, sources